blueprint:
  name: "Evening Wind Down"
  description: |
    ## Prepare for restful sleep with gradual dimming

    This blueprint helps you wind down in the evening by gradually reducing
    brightness and shifting to warm, sleep-friendly light. Blue light is
    minimized to support your natural sleep rhythm.

    ### Features
    - Gradual dimming over your chosen duration
    - Warm light only (2700K) to avoid blue light
    - Trigger at sunset or a fixed time
    - Support for multiple lights
    - Option to only run if lights are already on

    ### How It Works
    1. Starts at your chosen brightness with warm 2700K light
    2. Gradually dims every 2 minutes
    3. Ends at your target brightness (or turns off if set to 0%)

    > **Tip**: Start 1-2 hours before bedtime for best results.
  domain: automation
  source_url: https://github.com/moag1000/beurer_daylight_lamps/blob/main/blueprints/automation/beurer_daylight_lamps/evening_wind_down.yaml
  author: moag1000

  input:
    # ═══════════════════════════════════════════════════════════════════════════
    # LIGHTS SECTION
    # ═══════════════════════════════════════════════════════════════════════════
    beurer_light:
      name: "Primary Beurer Lamp"
      description: "Select your main Beurer daylight therapy lamp"
      selector:
        entity:
          filter:
            - integration: beurer_daylight_lamps
              domain: light

    additional_lights:
      name: "Additional Lights (Optional)"
      description: |
        Add more lights to include in the wind-down routine.
        Supports any light in Home Assistant (WiZ, Hue, WLED, etc.)
      default: []
      selector:
        entity:
          multiple: true
          filter:
            - domain: light

    sync_mode:
      name: "Sync Mode for Additional Lights"
      description: "How should additional lights follow the Beurer lamp?"
      default: "full_sync"
      selector:
        select:
          options:
            - label: "Full sync - Match brightness AND color temperature"
              value: "full_sync"
            - label: "Brightness only - Keep their current color"
              value: "brightness_only"
            - label: "On/Off only - Use their default settings"
              value: "on_off_only"
          mode: dropdown

    # ═══════════════════════════════════════════════════════════════════════════
    # TRIGGER SECTION
    # ═══════════════════════════════════════════════════════════════════════════
    trigger_type:
      name: "When to Start"
      description: "Choose what triggers the wind-down routine"
      default: "sunset"
      selector:
        select:
          options:
            - label: "At sunset (adjusts automatically)"
              value: "sunset"
            - label: "At a fixed time"
              value: "fixed"
          mode: dropdown

    fixed_time:
      name: "Fixed Time"
      description: "Start time when using fixed schedule (ignored if sunset is selected)"
      default: "20:00:00"
      selector:
        time:

    sunset_offset:
      name: "Sunset Offset"
      description: |
        Adjust timing relative to sunset.
        Negative = before sunset, Positive = after sunset
      default: 0
      selector:
        number:
          min: -120
          max: 120
          step: 15
          unit_of_measurement: "min"
          mode: slider

    # ═══════════════════════════════════════════════════════════════════════════
    # DIMMING SETTINGS
    # ═══════════════════════════════════════════════════════════════════════════
    wind_down_duration:
      name: "Wind-down Duration"
      description: |
        How long should the dimming process take?

        Tip: 30-60 minutes gives a gentle transition.
      default: 60
      selector:
        number:
          min: 15
          max: 120
          step: 15
          unit_of_measurement: "min"
          mode: slider

    start_brightness:
      name: "Starting Brightness"
      description: "Brightness level at the beginning of wind-down"
      default: 80
      selector:
        number:
          min: 30
          max: 100
          step: 10
          unit_of_measurement: "%"
          mode: slider

    end_brightness:
      name: "Ending Brightness"
      description: |
        Brightness level at the end.
        Set to 0% to turn off completely when done.
      default: 10
      selector:
        number:
          min: 0
          max: 50
          step: 5
          unit_of_measurement: "%"
          mode: slider

    # ═══════════════════════════════════════════════════════════════════════════
    # BEHAVIOR OPTIONS
    # ═══════════════════════════════════════════════════════════════════════════
    only_if_on:
      name: "Only If Already On"
      description: |
        When enabled, wind-down only starts if the lamp is already on.
        Useful to avoid turning on lights in empty rooms.
      default: true
      selector:
        boolean:

# ═══════════════════════════════════════════════════════════════════════════════
# VARIABLES
# ═══════════════════════════════════════════════════════════════════════════════
variables:
  beurer: !input beurer_light
  extras: !input additional_lights
  sync: !input sync_mode
  trigger_mode: !input trigger_type
  duration_mins: !input wind_down_duration
  brightness_start: !input start_brightness
  brightness_end: !input end_brightness
  check_state: !input only_if_on

  # Helper: all lights combined
  all_lights: >
    {{ [beurer] + (extras if extras else []) }}

  # Helper: has additional lights?
  has_extras: >
    {{ extras is defined and extras | length > 0 }}

  # Calculate dimming steps (one every 2 minutes)
  total_steps: "{{ (duration_mins / 2) | int }}"
  brightness_per_step: "{{ ((brightness_start - brightness_end) / total_steps) | float }}"

# ═══════════════════════════════════════════════════════════════════════════════
# TRIGGERS
# ═══════════════════════════════════════════════════════════════════════════════
trigger:
  - platform: sun
    event: sunset
    offset: !input sunset_offset
    id: sunset_trigger
  - platform: time
    at: !input fixed_time
    id: time_trigger

# ═══════════════════════════════════════════════════════════════════════════════
# CONDITIONS
# ═══════════════════════════════════════════════════════════════════════════════
condition:
  # Match trigger type
  - condition: or
    conditions:
      - condition: and
        conditions:
          - condition: template
            value_template: "{{ trigger_mode == 'sunset' }}"
          - condition: trigger
            id: sunset_trigger
      - condition: and
        conditions:
          - condition: template
            value_template: "{{ trigger_mode == 'fixed' }}"
          - condition: trigger
            id: time_trigger

  # Check if lamp should be on (if setting enabled)
  - condition: or
    conditions:
      - condition: template
        value_template: "{{ not check_state }}"
      - condition: state
        entity_id: !input beurer_light
        state: "on"

# ═══════════════════════════════════════════════════════════════════════════════
# ACTIONS
# ═══════════════════════════════════════════════════════════════════════════════
action:
  # ─────────────────────────────────────────────────────────────────────────────
  # INITIAL STATE: Set warm light at starting brightness
  # ─────────────────────────────────────────────────────────────────────────────
  - service: light.turn_on
    target:
      entity_id: "{{ beurer }}"
    data:
      brightness_pct: "{{ brightness_start }}"
      color_temp_kelvin: 2700

  - if:
      - condition: template
        value_template: "{{ has_extras }}"
    then:
      - choose:
          - conditions: "{{ sync == 'full_sync' }}"
            sequence:
              - service: light.turn_on
                target:
                  entity_id: "{{ extras }}"
                data:
                  brightness_pct: "{{ brightness_start }}"
                  color_temp_kelvin: 2700
          - conditions: "{{ sync == 'brightness_only' }}"
            sequence:
              - service: light.turn_on
                target:
                  entity_id: "{{ extras }}"
                data:
                  brightness_pct: "{{ brightness_start }}"
        default:
          - service: light.turn_on
            target:
              entity_id: "{{ extras }}"

  # ─────────────────────────────────────────────────────────────────────────────
  # GRADUAL DIMMING
  # ─────────────────────────────────────────────────────────────────────────────
  - repeat:
      count: "{{ total_steps }}"
      sequence:
        - delay:
            minutes: 2
        - variables:
            current_brightness: "{{ (brightness_start - (brightness_per_step * repeat.index)) | int | max(brightness_end) }}"

        # Update Beurer lamp
        - service: light.turn_on
          target:
            entity_id: "{{ beurer }}"
          data:
            brightness_pct: "{{ current_brightness }}"
            color_temp_kelvin: 2700

        # Update additional lights
        - if:
            - condition: template
              value_template: "{{ has_extras }}"
          then:
            - choose:
                - conditions: "{{ sync == 'full_sync' }}"
                  sequence:
                    - service: light.turn_on
                      target:
                        entity_id: "{{ extras }}"
                      data:
                        brightness_pct: "{{ current_brightness }}"
                        color_temp_kelvin: 2700
                - conditions: "{{ sync == 'brightness_only' }}"
                  sequence:
                    - service: light.turn_on
                      target:
                        entity_id: "{{ extras }}"
                      data:
                        brightness_pct: "{{ current_brightness }}"

  # ─────────────────────────────────────────────────────────────────────────────
  # FINAL ACTION: Turn off if end brightness is 0
  # ─────────────────────────────────────────────────────────────────────────────
  - if:
      - condition: template
        value_template: "{{ brightness_end == 0 }}"
    then:
      - service: light.turn_off
        target:
          entity_id: "{{ all_lights }}"

mode: single
max_exceeded: silent
