blueprint:
  name: "Focus Work Session"
  description: |
    ## Optimize your workspace for deep concentration

    This blueprint sets up bright, cool light to help you stay focused during
    work sessions. The alerting light temperature promotes concentration and
    can help combat afternoon fatigue.

    ### Features
    - Cool, alerting light (4000K-6500K)
    - Optional Pomodoro-style break reminders
    - Support for multiple lights
    - Configurable session duration
    - Multiple end behaviors
    - Automatic abort if lights are turned off manually

    ### How Pomodoro Breaks Work
    When enabled, the lights briefly dim and warm up every N minutes as a
    visual reminder to take a short break. After 10 seconds, they return
    to focus mode.

    > **Tip**: For best results, position your Beurer lamp at eye level,
    > about 50-75cm from your face.
  domain: automation
  source_url: https://github.com/moag1000/beurer_daylight_lamps/blob/main/blueprints/automation/beurer_daylight_lamps/focus_work_session.yaml
  author: moag1000
  homeassistant:
    min_version: "2023.9.0"

  input:
    # ═══════════════════════════════════════════════════════════════════════════
    # LIGHTS SECTION
    # ═══════════════════════════════════════════════════════════════════════════
    beurer_light:
      name: "Primary Beurer Lamp"
      description: "Select your main Beurer daylight therapy lamp"
      selector:
        entity:
          filter:
            - integration: beurer_daylight_lamps
              domain: light

    additional_lights:
      name: "Additional Lights (Optional)"
      description: |
        Add more lights to your focus workspace.
        Supports any light in Home Assistant (desk lamps, ceiling lights, etc.)
      default: []
      selector:
        entity:
          multiple: true
          filter:
            - domain: light

    sync_mode:
      name: "Sync Mode for Additional Lights"
      description: "How should additional lights follow the Beurer lamp?"
      default: "full_sync"
      selector:
        select:
          options:
            - label: "Full sync - Match brightness AND color temperature"
              value: "full_sync"
            - label: "Brightness only - Keep their current color"
              value: "brightness_only"
            - label: "On/Off only - Use their default settings"
              value: "on_off_only"
          mode: dropdown

    # ═══════════════════════════════════════════════════════════════════════════
    # TRIGGER SECTION
    # ═══════════════════════════════════════════════════════════════════════════
    trigger_entity:
      name: "Trigger Entity (Optional)"
      description: |
        Entity that starts the focus session when turned on.
        Examples: input_boolean, button, or leave empty to use time trigger.
      default: []
      selector:
        entity:

    use_time_trigger:
      name: "Use Time Trigger Instead"
      description: "Enable to start at a fixed time instead of entity trigger"
      default: false
      selector:
        boolean:

    manual_trigger_time:
      name: "Fixed Start Time"
      description: "Start time when using time trigger (ignored if disabled above)"
      default: "09:00:00"
      selector:
        time:

    # ═══════════════════════════════════════════════════════════════════════════
    # LIGHT SETTINGS
    # ═══════════════════════════════════════════════════════════════════════════
    focus_brightness:
      name: "Focus Brightness"
      description: |
        Brightness level during focus work.
        Higher brightness = more alerting effect.
      default: 90
      selector:
        number:
          min: 50
          max: 100
          step: 5
          unit_of_measurement: "%"
          mode: slider

    color_temperature:
      name: "Color Temperature"
      description: |
        Light temperature during focus work.
        Higher = cooler/bluer = more alerting.

        - 4000K: Neutral white (balanced)
        - 5000K: Daylight (recommended)
        - 6500K: Cool daylight (most alerting)
      default: 5000
      selector:
        number:
          min: 4000
          max: 6500
          step: 500
          unit_of_measurement: "K"
          mode: slider

    # ═══════════════════════════════════════════════════════════════════════════
    # SESSION SETTINGS
    # ═══════════════════════════════════════════════════════════════════════════
    session_duration:
      name: "Session Duration"
      description: "Total length of the focus session"
      default: 60
      selector:
        number:
          min: 15
          max: 120
          step: 15
          unit_of_measurement: "min"
          mode: slider

    # ═══════════════════════════════════════════════════════════════════════════
    # POMODORO BREAK SETTINGS
    # ═══════════════════════════════════════════════════════════════════════════
    enable_breaks:
      name: "Enable Break Reminders"
      description: |
        Dim lights briefly as a visual reminder to take a break.
        Uses the Pomodoro technique timing by default.
      default: false
      selector:
        boolean:

    break_interval:
      name: "Break Interval"
      description: |
        Minutes between break reminders.
        Classic Pomodoro = 25 minutes.
      default: 25
      selector:
        number:
          min: 15
          max: 45
          step: 5
          unit_of_measurement: "min"
          mode: slider

    # ═══════════════════════════════════════════════════════════════════════════
    # END BEHAVIOR
    # ═══════════════════════════════════════════════════════════════════════════
    end_action:
      name: "After Session Ends"
      description: "What should happen when the focus session is complete?"
      default: "relax"
      selector:
        select:
          options:
            - label: "Switch to relaxing warm light (2700K, 50%)"
              value: "relax"
            - label: "Turn off all lights"
              value: "off"
            - label: "Stay on (keep focus light)"
              value: "stay_on"
          mode: dropdown

# ═══════════════════════════════════════════════════════════════════════════════
# VARIABLES
# ═══════════════════════════════════════════════════════════════════════════════
variables:
  beurer: !input beurer_light
  extras: !input additional_lights
  sync: !input sync_mode
  focus_bright: !input focus_brightness
  focus_temp: !input color_temperature
  session_mins: !input session_duration
  breaks_enabled: !input enable_breaks
  break_mins: !input break_interval
  end_behavior: !input end_action
  use_time: !input use_time_trigger

  # Helper: all lights combined
  all_lights: >
    {{ [beurer] + (extras if extras else []) }}

  # Helper: has additional lights?
  has_extras: >
    {{ extras is defined and extras | length > 0 }}

  # Calculate number of breaks in session
  # For 60 min session with 25 min intervals: 60/25 = 2.4 -> 2 full intervals = 2 breaks
  # (We take a break AFTER each work interval, except the last one ends the session)
  total_breaks: "{{ (session_mins / break_mins) | int }}"

  # Minutes in the final work period (after the last break)
  final_period_mins: "{{ session_mins - (total_breaks * break_mins) }}"

# ═══════════════════════════════════════════════════════════════════════════════
# TRIGGERS
# ═══════════════════════════════════════════════════════════════════════════════
trigger:
  - platform: state
    entity_id: !input trigger_entity
    to: "on"
    id: entity_trigger
  - platform: time
    at: !input manual_trigger_time
    id: time_trigger

# ═══════════════════════════════════════════════════════════════════════════════
# CONDITIONS
# ═══════════════════════════════════════════════════════════════════════════════
condition:
  - condition: or
    conditions:
      - condition: and
        conditions:
          - condition: template
            value_template: "{{ not use_time }}"
          - condition: trigger
            id: entity_trigger
      - condition: and
        conditions:
          - condition: template
            value_template: "{{ use_time }}"
          - condition: trigger
            id: time_trigger

# ═══════════════════════════════════════════════════════════════════════════════
# ACTIONS
# ═══════════════════════════════════════════════════════════════════════════════
action:
  # ─────────────────────────────────────────────────────────────────────────────
  # START FOCUS LIGHT
  # ─────────────────────────────────────────────────────────────────────────────
  - service: light.turn_on
    target:
      entity_id: "{{ beurer }}"
    data:
      brightness_pct: "{{ focus_bright }}"
      color_temp_kelvin: "{{ focus_temp }}"
      transition: 3

  - if:
      - condition: template
        value_template: "{{ has_extras }}"
    then:
      - choose:
          - conditions: "{{ sync == 'full_sync' }}"
            sequence:
              - service: light.turn_on
                target:
                  entity_id: "{{ extras }}"
                data:
                  brightness_pct: "{{ focus_bright }}"
                  color_temp_kelvin: "{{ focus_temp }}"
                  transition: 3
          - conditions: "{{ sync == 'brightness_only' }}"
            sequence:
              - service: light.turn_on
                target:
                  entity_id: "{{ extras }}"
                data:
                  brightness_pct: "{{ focus_bright }}"
                  transition: 3
        default:
          - service: light.turn_on
            target:
              entity_id: "{{ extras }}"

  # Wait for initial setup
  - delay:
      seconds: 5

  # ─────────────────────────────────────────────────────────────────────────────
  # MAIN SESSION (with optional breaks)
  # ─────────────────────────────────────────────────────────────────────────────
  - choose:
      # WITH BREAK REMINDERS
      - conditions:
          - condition: template
            value_template: "{{ breaks_enabled and total_breaks > 0 }}"
        sequence:
          - repeat:
              count: "{{ total_breaks }}"
              sequence:
                # Check if lamp was turned off manually - abort if so
                - condition: state
                  entity_id: !input beurer_light
                  state: "on"

                # Work period
                - delay:
                    minutes: "{{ break_mins }}"

                # Check again before break reminder
                - condition: state
                  entity_id: !input beurer_light
                  state: "on"

                # Break reminder: dim and warm briefly with smooth transition
                - service: light.turn_on
                  target:
                    entity_id: "{{ beurer }}"
                  data:
                    brightness_pct: 30
                    color_temp_kelvin: 3500
                    transition: 2

                - if:
                    - condition: template
                      value_template: "{{ has_extras and sync in ['full_sync', 'brightness_only'] }}"
                  then:
                    - service: light.turn_on
                      target:
                        entity_id: "{{ extras }}"
                      data:
                        brightness_pct: 30
                        color_temp_kelvin: "{{ 3500 if sync == 'full_sync' else focus_temp }}"
                        transition: 2

                # Brief pause for break (10 seconds)
                - delay:
                    seconds: 10

                # Back to focus light with smooth transition
                - service: light.turn_on
                  target:
                    entity_id: "{{ beurer }}"
                  data:
                    brightness_pct: "{{ focus_bright }}"
                    color_temp_kelvin: "{{ focus_temp }}"
                    transition: 2

                - if:
                    - condition: template
                      value_template: "{{ has_extras }}"
                  then:
                    - choose:
                        - conditions: "{{ sync == 'full_sync' }}"
                          sequence:
                            - service: light.turn_on
                              target:
                                entity_id: "{{ extras }}"
                              data:
                                brightness_pct: "{{ focus_bright }}"
                                color_temp_kelvin: "{{ focus_temp }}"
                                transition: 2
                        - conditions: "{{ sync == 'brightness_only' }}"
                          sequence:
                            - service: light.turn_on
                              target:
                                entity_id: "{{ extras }}"
                              data:
                                brightness_pct: "{{ focus_bright }}"
                                transition: 2

          # Check before final work period
          - condition: state
            entity_id: !input beurer_light
            state: "on"

          # Final work period (remaining time after last break)
          - if:
              - condition: template
                value_template: "{{ final_period_mins > 0 }}"
            then:
              - delay:
                  minutes: "{{ final_period_mins }}"

    # WITHOUT BREAKS - just wait for session duration
    default:
      - delay:
          minutes: "{{ session_mins }}"

  # ─────────────────────────────────────────────────────────────────────────────
  # END ACTION
  # ─────────────────────────────────────────────────────────────────────────────
  # Only execute end action if lamp is still on
  - condition: state
    entity_id: !input beurer_light
    state: "on"

  - choose:
      # Turn off
      - conditions: "{{ end_behavior == 'off' }}"
        sequence:
          - service: light.turn_off
            target:
              entity_id: "{{ all_lights }}"
            data:
              transition: 5

      # Switch to relaxing light
      - conditions: "{{ end_behavior == 'relax' }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ beurer }}"
            data:
              brightness_pct: 50
              color_temp_kelvin: 2700
              transition: 10

          - if:
              - condition: template
                value_template: "{{ has_extras }}"
            then:
              - choose:
                  - conditions: "{{ sync == 'full_sync' }}"
                    sequence:
                      - service: light.turn_on
                        target:
                          entity_id: "{{ extras }}"
                        data:
                          brightness_pct: 50
                          color_temp_kelvin: 2700
                          transition: 10
                  - conditions: "{{ sync == 'brightness_only' }}"
                    sequence:
                      - service: light.turn_on
                        target:
                          entity_id: "{{ extras }}"
                        data:
                          brightness_pct: 50
                          transition: 10

      # Stay on (do nothing)

mode: single
max_exceeded: silent
