blueprint:
  name: "Morning Light Therapy"
  description: |
    ## Wake up naturally with simulated sunrise

    This blueprint creates a gentle wake-up experience by gradually increasing
    brightness and color temperature, simulating a natural sunrise. After the
    sunrise phase, the lamp maintains bright daylight for your therapy session.

    ### Features
    - Gradual sunrise simulation (warm to cool light)
    - Smooth transitions between brightness levels
    - Configurable therapy duration at full brightness
    - Support for multiple lights (sync additional lamps)
    - Flexible scheduling (workdays, weekends, or daily)
    - Automatic abort if lights are turned off manually

    ### Recommended Settings
    - **Sunrise**: 15-20 minutes for a natural wake-up
    - **Therapy**: 20-30 minutes at full brightness (5300K)

    > **Note**: This is a lifestyle/wellness feature, not a medical device.
  domain: automation
  source_url: https://github.com/moag1000/beurer_daylight_lamps/blob/main/blueprints/automation/beurer_daylight_lamps/morning_light_therapy.yaml
  author: moag1000
  homeassistant:
    min_version: "2023.9.0"

  input:
    beurer_light:
      name: "Primary Beurer Lamp"
      description: "Select your main Beurer daylight therapy lamp"
      selector:
        entity:
          filter:
            - integration: beurer_daylight_lamps
              domain: light

    additional_lights:
      name: "Additional Lights (Optional)"
      description: |
        Add more lights to sync with your Beurer lamp.
        Supports any light in Home Assistant (WiZ, Hue, WLED, etc.)
      default: []
      selector:
        entity:
          multiple: true
          filter:
            - domain: light

    sync_mode:
      name: "Sync Mode for Additional Lights"
      description: "How should additional lights follow the Beurer lamp?"
      default: "full_sync"
      selector:
        select:
          options:
            - label: "Full sync - Match brightness AND color temperature"
              value: "full_sync"
            - label: "Brightness only - Keep their current color"
              value: "brightness_only"
            - label: "On/Off only - Use their default settings"
              value: "on_off_only"

    wake_time:
      name: "Wake-up Time"
      description: "When should the sunrise begin? (Light starts dim at this time)"
      default: "06:30:00"
      selector:
        time:

    schedule_days:
      name: "Active Days"
      description: "Which days should this automation run?"
      default: "workdays"
      selector:
        select:
          options:
            - label: "Workdays only (Mon-Fri)"
              value: "workdays"
            - label: "Weekends only (Sat-Sun)"
              value: "weekends"
            - label: "Every day"
              value: "daily"

    sunrise_duration:
      name: "Sunrise Duration"
      description: |
        How long should the sunrise simulation take?
        Set to 0 to skip sunrise and start directly at full brightness.
        Tip: 15-20 minutes feels most natural.
      default: 15
      selector:
        number:
          min: 0
          max: 30
          step: 5
          unit_of_measurement: "min"

    therapy_duration:
      name: "Therapy Duration"
      description: |
        How long to maintain full brightness (5300K) after sunrise?
        Typical sessions are 20-30 minutes.
      default: 30
      selector:
        number:
          min: 10
          max: 60
          step: 5
          unit_of_measurement: "min"

    end_action:
      name: "After Session Ends"
      description: "What should happen when the therapy session is complete?"
      default: "off"
      selector:
        select:
          options:
            - label: "Turn off all lights"
              value: "off"
            - label: "Stay on at full brightness"
              value: "stay_on"
            - label: "Switch to comfortable reading light (4000K, 80%)"
              value: "reading"

variables:
  beurer: !input beurer_light
  extras: !input additional_lights
  sync: !input sync_mode
  sunrise_mins: !input sunrise_duration
  therapy_mins: !input therapy_duration
  schedule: !input schedule_days
  end_behavior: !input end_action

  # Calculate steps: one update every 30 seconds
  total_steps: "{{ (sunrise_mins * 2) | int if sunrise_mins > 0 else 0 }}"

  # All lights for turning off
  all_lights: "{{ [beurer] + (extras if extras else []) }}"

  # Check if we have extras
  has_extras: "{{ extras is defined and extras | length > 0 }}"

  # Helper to check light capabilities (used in templates)
  # supported_color_modes can include: onoff, brightness, color_temp, hs, rgb, rgbw, rgbww, white, xy
  ct_modes: "{{ ['color_temp', 'rgbww', 'white'] }}"
  brightness_modes: "{{ ['brightness', 'color_temp', 'hs', 'rgb', 'rgbw', 'rgbww', 'white', 'xy'] }}"

trigger:
  - platform: time
    at: !input wake_time

condition:
  - condition: template
    value_template: >
      {% set day = now().weekday() %}
      {{ (schedule == 'daily') or
         (schedule == 'workdays' and day < 5) or
         (schedule == 'weekends' and day >= 5) }}

action:
  # =========================================================================
  # PHASE 1: SUNRISE SIMULATION (gradual increase over sunrise_mins)
  # =========================================================================
  - if:
      - condition: template
        value_template: "{{ sunrise_mins > 0 }}"
    then:
      # Start very dim and warm
      - service: light.turn_on
        target:
          entity_id: "{{ beurer }}"
        data:
          brightness_pct: 1
          color_temp_kelvin: 2700
          transition: 2

      # Additional lights: initial dim state (with capability detection)
      - if:
          - condition: template
            value_template: "{{ has_extras }}"
        then:
          - repeat:
              for_each: "{{ extras }}"
              sequence:
                - variables:
                    light_entity: "{{ repeat.item }}"
                    light_modes: "{{ state_attr(light_entity, 'supported_color_modes') or [] }}"
                    supports_brightness: "{{ light_modes | select('in', brightness_modes) | list | length > 0 }}"
                    supports_ct: "{{ light_modes | select('in', ct_modes) | list | length > 0 }}"
                - choose:
                    # Full sync with color temp support
                    - conditions: "{{ sync == 'full_sync' and supports_ct and supports_brightness }}"
                      sequence:
                        - service: light.turn_on
                          target:
                            entity_id: "{{ light_entity }}"
                          data:
                            brightness_pct: 1
                            color_temp_kelvin: 2700
                            transition: 2
                    # Full sync but no CT - just brightness
                    - conditions: "{{ sync == 'full_sync' and supports_brightness }}"
                      sequence:
                        - service: light.turn_on
                          target:
                            entity_id: "{{ light_entity }}"
                          data:
                            brightness_pct: 1
                            transition: 2
                    # Brightness only mode
                    - conditions: "{{ sync == 'brightness_only' and supports_brightness }}"
                      sequence:
                        - service: light.turn_on
                          target:
                            entity_id: "{{ light_entity }}"
                          data:
                            brightness_pct: 1
                            transition: 2
                  # Default: on/off only or no brightness support
                  default:
                    - service: light.turn_on
                      target:
                        entity_id: "{{ light_entity }}"

      # Wait for initial turn on
      - delay:
          seconds: 3

      # Gradual sunrise loop
      - repeat:
          count: "{{ total_steps }}"
          sequence:
            # Check if lamp was turned off manually - abort if so
            # Allow "unavailable" state to continue (temporary BLE disconnect)
            - condition: template
              value_template: >
                {{ states(beurer) in ['on', 'unavailable'] }}

            # Calculate current values based on progress
            # Progress goes from 1/total_steps to total_steps/total_steps (1.0)
            - variables:
                step: "{{ repeat.index }}"
                progress: "{{ step / total_steps }}"
                # Brightness: 1% -> 100% (exponential feels more natural)
                target_brightness: "{{ (1 + (99 * (progress ** 1.5))) | round(0) | int }}"
                # Color temp: 2700K -> 5300K (linear)
                target_temp: "{{ (2700 + (2600 * progress)) | round(0) | int }}"

            # Update Beurer lamp with smooth transition
            - service: light.turn_on
              target:
                entity_id: "{{ beurer }}"
              data:
                brightness_pct: "{{ target_brightness }}"
                color_temp_kelvin: "{{ target_temp }}"
                transition: 25

            # Update additional lights (with capability detection)
            - if:
                - condition: template
                  value_template: "{{ has_extras }}"
              then:
                - repeat:
                    for_each: "{{ extras }}"
                    sequence:
                      - variables:
                          light_entity: "{{ repeat.item }}"
                          light_modes: "{{ state_attr(light_entity, 'supported_color_modes') or [] }}"
                          supports_brightness: "{{ light_modes | select('in', brightness_modes) | list | length > 0 }}"
                          supports_ct: "{{ light_modes | select('in', ct_modes) | list | length > 0 }}"
                      - choose:
                          # Full sync with color temp support
                          - conditions: "{{ sync == 'full_sync' and supports_ct and supports_brightness }}"
                            sequence:
                              - service: light.turn_on
                                target:
                                  entity_id: "{{ light_entity }}"
                                data:
                                  brightness_pct: "{{ target_brightness }}"
                                  color_temp_kelvin: "{{ target_temp }}"
                                  transition: 25
                          # Full sync but no CT - just brightness
                          - conditions: "{{ sync == 'full_sync' and supports_brightness }}"
                            sequence:
                              - service: light.turn_on
                                target:
                                  entity_id: "{{ light_entity }}"
                                data:
                                  brightness_pct: "{{ target_brightness }}"
                                  transition: 25
                          # Brightness only mode
                          - conditions: "{{ sync == 'brightness_only' and supports_brightness }}"
                            sequence:
                              - service: light.turn_on
                                target:
                                  entity_id: "{{ light_entity }}"
                                data:
                                  brightness_pct: "{{ target_brightness }}"
                                  transition: 25
                        # Default: on/off only - light is already on, no action needed

            # Wait before next step (30 seconds minus transition overlap)
            - delay:
                seconds: 30

  # =========================================================================
  # PHASE 2: FULL THERAPY BRIGHTNESS
  # =========================================================================
  # Only continue if lamp is still on (or temporarily unavailable)
  - condition: template
    value_template: >
      {{ states(beurer) in ['on', 'unavailable'] }}

  # Set full therapy brightness
  - service: light.turn_on
    target:
      entity_id: "{{ beurer }}"
    data:
      brightness_pct: 100
      color_temp_kelvin: 5300
      transition: 5

  # Additional lights: therapy brightness (with capability detection)
  - if:
      - condition: template
        value_template: "{{ has_extras }}"
    then:
      - repeat:
          for_each: "{{ extras }}"
          sequence:
            - variables:
                light_entity: "{{ repeat.item }}"
                light_modes: "{{ state_attr(light_entity, 'supported_color_modes') or [] }}"
                supports_brightness: "{{ light_modes | select('in', brightness_modes) | list | length > 0 }}"
                supports_ct: "{{ light_modes | select('in', ct_modes) | list | length > 0 }}"
            - choose:
                # Full sync with color temp support
                - conditions: "{{ sync == 'full_sync' and supports_ct and supports_brightness }}"
                  sequence:
                    - service: light.turn_on
                      target:
                        entity_id: "{{ light_entity }}"
                      data:
                        brightness_pct: 100
                        color_temp_kelvin: 5300
                        transition: 5
                # Full sync but no CT - just brightness
                - conditions: "{{ sync == 'full_sync' and supports_brightness }}"
                  sequence:
                    - service: light.turn_on
                      target:
                        entity_id: "{{ light_entity }}"
                      data:
                        brightness_pct: 100
                        transition: 5
                # Brightness only mode
                - conditions: "{{ sync == 'brightness_only' and supports_brightness }}"
                  sequence:
                    - service: light.turn_on
                      target:
                        entity_id: "{{ light_entity }}"
                      data:
                        brightness_pct: 100
                        transition: 5
              # Default: on/off only - light is already on

  # Wait for therapy duration
  - delay:
      minutes: "{{ therapy_mins }}"

  # =========================================================================
  # PHASE 3: END ACTION
  # =========================================================================
  # Only execute end action if lamp is still on (or temporarily unavailable)
  - condition: template
    value_template: >
      {{ states(beurer) in ['on', 'unavailable'] }}

  - choose:
      # Turn off all lights
      - conditions: "{{ end_behavior == 'off' }}"
        sequence:
          - service: light.turn_off
            target:
              entity_id: "{{ all_lights }}"
            data:
              transition: 5

      # Switch to reading light
      - conditions: "{{ end_behavior == 'reading' }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ beurer }}"
            data:
              brightness_pct: 80
              color_temp_kelvin: 4000
              transition: 10
          # Additional lights: reading mode (with capability detection)
          - if:
              - condition: template
                value_template: "{{ has_extras }}"
            then:
              - repeat:
                  for_each: "{{ extras }}"
                  sequence:
                    - variables:
                        light_entity: "{{ repeat.item }}"
                        light_modes: "{{ state_attr(light_entity, 'supported_color_modes') or [] }}"
                        supports_brightness: "{{ light_modes | select('in', brightness_modes) | list | length > 0 }}"
                        supports_ct: "{{ light_modes | select('in', ct_modes) | list | length > 0 }}"
                    - choose:
                        # Full sync with color temp support
                        - conditions: "{{ sync == 'full_sync' and supports_ct and supports_brightness }}"
                          sequence:
                            - service: light.turn_on
                              target:
                                entity_id: "{{ light_entity }}"
                              data:
                                brightness_pct: 80
                                color_temp_kelvin: 4000
                                transition: 10
                        # Full sync but no CT - just brightness
                        - conditions: "{{ sync == 'full_sync' and supports_brightness }}"
                          sequence:
                            - service: light.turn_on
                              target:
                                entity_id: "{{ light_entity }}"
                              data:
                                brightness_pct: 80
                                transition: 10
                        # Brightness only mode
                        - conditions: "{{ sync == 'brightness_only' and supports_brightness }}"
                          sequence:
                            - service: light.turn_on
                              target:
                                entity_id: "{{ light_entity }}"
                              data:
                                brightness_pct: 80
                                transition: 10
                      # Default: on/off only - light stays as is

      # Stay on: do nothing (lights remain at therapy brightness)

mode: single
max_exceeded: silent
