blueprint:
  name: "Morning Light Therapy"
  description: |
    ## Wake up naturally with simulated sunrise

    This blueprint creates a gentle wake-up experience by gradually increasing
    brightness and color temperature, simulating a natural sunrise. After the
    sunrise phase, the lamp maintains bright daylight for your therapy session.

    ### Features
    - Realistic sunrise colors (deep orange → warm white → daylight)
    - Smooth transitions between brightness levels
    - Configurable therapy duration at full brightness
    - Support for multiple lights (sync additional lamps)
    - Flexible scheduling (workdays, weekends, or daily)
    - Automatic abort if lights are turned off manually

    ### Recommended Settings
    - **Sunrise**: 15-20 minutes for a natural wake-up
    - **Therapy**: 20-30 minutes at full brightness (native white mode)

    > **Note**: This is a lifestyle/wellness feature, not a medical device.
  domain: automation
  source_url: https://github.com/moag1000/beurer_daylight_lamps/blob/main/blueprints/automation/beurer_daylight_lamps/morning_light_therapy.yaml
  author: moag1000
  homeassistant:
    min_version: "2023.9.0"

  input:
    beurer_light:
      name: "Primary Beurer Lamp"
      description: "Select your main Beurer daylight therapy lamp"
      selector:
        entity:
          filter:
            - integration: beurer_daylight_lamps
              domain: light

    additional_lights:
      name: "Additional Lights (Optional)"
      description: |
        Add more lights to sync with your Beurer lamp.
        Supports any light in Home Assistant (WiZ, Hue, WLED, etc.)
      default: []
      selector:
        entity:
          multiple: true
          filter:
            - domain: light

    sync_mode:
      name: "Sync Mode for Additional Lights"
      description: "How should additional lights follow the Beurer lamp?"
      default: "full_sync"
      selector:
        select:
          options:
            - label: "Full sync - Match brightness AND color"
              value: "full_sync"
            - label: "Brightness only - Keep their current color"
              value: "brightness_only"
            - label: "On/Off only - Use their default settings"
              value: "on_off_only"

    wake_time:
      name: "Wake-up Time"
      description: "When should the sunrise begin? (Light starts dim at this time)"
      default: "06:30:00"
      selector:
        time:

    schedule_days:
      name: "Active Days"
      description: "Which days should this automation run?"
      default: "workdays"
      selector:
        select:
          options:
            - label: "Workdays only (Mon-Fri)"
              value: "workdays"
            - label: "Weekends only (Sat-Sun)"
              value: "weekends"
            - label: "Every day"
              value: "daily"

    sunrise_duration:
      name: "Sunrise Duration"
      description: |
        How long should the sunrise simulation take?
        Set to 0 to skip sunrise and start directly at full brightness.
        Tip: 15-20 minutes feels most natural.
      default: 15
      selector:
        number:
          min: 0
          max: 30
          step: 5
          unit_of_measurement: "min"

    therapy_duration:
      name: "Therapy Duration"
      description: |
        How long to maintain full brightness after sunrise?
        Uses native white mode (5300K) for optimal therapy.
        Typical sessions are 20-30 minutes.
      default: 30
      selector:
        number:
          min: 10
          max: 60
          step: 5
          unit_of_measurement: "min"

    end_action:
      name: "After Session Ends"
      description: "What should happen when the therapy session is complete?"
      default: "off"
      selector:
        select:
          options:
            - label: "Turn off all lights"
              value: "off"
            - label: "Stay on at full brightness"
              value: "stay_on"
            - label: "Switch to comfortable reading light (4000K, 80%)"
              value: "reading"

variables:
  beurer: !input beurer_light
  extras: !input additional_lights
  sync: !input sync_mode
  sunrise_mins: !input sunrise_duration
  therapy_mins: !input therapy_duration
  schedule: !input schedule_days
  end_behavior: !input end_action

  # Calculate steps: one update every 30 seconds
  total_steps: "{{ (sunrise_mins * 2) | int if sunrise_mins > 0 else 0 }}"

  # All lights for turning off
  all_lights: "{{ [beurer] + (extras if extras is list else []) }}"

  # Check if we have extras - more robust check
  has_extras: "{{ extras is list and extras | length > 0 }}"

  # Sunrise color gradient (RGB values for realistic sunrise)
  # Progress 0.0 -> 1.0 maps through these colors:
  # Deep orange -> Orange -> Warm yellow -> Warm white -> Neutral -> Daylight
  sunrise_colors:
    - [255, 100, 20]   # 0.0 - Deep orange/red (like early sunrise)
    - [255, 140, 40]   # 0.2 - Orange
    - [255, 180, 80]   # 0.4 - Warm yellow/orange
    - [255, 210, 140]  # 0.6 - Warm white
    - [255, 235, 200]  # 0.8 - Neutral warm
    - [255, 250, 240]  # 1.0 - Near white (before switch to native white)

trigger:
  - platform: time
    at: !input wake_time

condition:
  - condition: template
    value_template: >
      {% set day = now().weekday() %}
      {{ (schedule == 'daily') or
         (schedule == 'workdays' and day < 5) or
         (schedule == 'weekends' and day >= 5) }}

action:
  # =========================================================================
  # PHASE 1: SUNRISE SIMULATION (gradual increase over sunrise_mins)
  # =========================================================================
  - if:
      - condition: template
        value_template: "{{ sunrise_mins > 0 }}"
    then:
      # Start very dim with deep orange (like early sunrise)
      - service: light.turn_on
        target:
          entity_id: "{{ beurer }}"
        data:
          brightness_pct: 1
          rgb_color: [255, 100, 20]
          transition: 2

      # Additional lights: initial dim state
      - if:
          - condition: template
            value_template: "{{ has_extras }}"
        then:
          - service: light.turn_on
            target:
              entity_id: "{{ extras }}"
            data:
              brightness_pct: 1
              color_temp_kelvin: 2000
              transition: 2

      # Wait for initial turn on
      - delay:
          seconds: 3

      # Gradual sunrise loop
      - repeat:
          count: "{{ total_steps }}"
          sequence:
            # Check if lamp was turned off manually - abort if so
            # Allow "unavailable" state to continue (temporary BLE disconnect)
            - condition: template
              value_template: >
                {{ states(beurer) in ['on', 'unavailable'] }}

            # Calculate current values based on progress
            - variables:
                step: "{{ repeat.index }}"
                progress: "{{ step / total_steps }}"
                # Brightness: 1% -> 95% (exponential feels more natural)
                # We stop at 95% to leave room for the white mode boost
                target_brightness: "{{ (1 + (94 * (progress ** 1.5))) | round(0) | int }}"
                # Color: interpolate through sunrise gradient
                # Map progress to color index (0-5)
                color_idx: "{{ (progress * 5) | int }}"
                color_blend: "{{ (progress * 5) - color_idx }}"
                # Get colors for interpolation
                c1: "{{ sunrise_colors[color_idx | int] }}"
                c2: "{{ sunrise_colors[(color_idx | int + 1) | min(5)] }}"
                # Interpolate RGB
                target_r: "{{ (c1[0] + (c2[0] - c1[0]) * color_blend) | round(0) | int }}"
                target_g: "{{ (c1[1] + (c2[1] - c1[1]) * color_blend) | round(0) | int }}"
                target_b: "{{ (c1[2] + (c2[2] - c1[2]) * color_blend) | round(0) | int }}"
                # Color temp for additional lights (2000K -> 5000K)
                target_temp: "{{ (2000 + (3000 * progress)) | round(0) | int }}"

            # Update Beurer lamp with RGB color (stays in RGB mode)
            - service: light.turn_on
              target:
                entity_id: "{{ beurer }}"
              data:
                brightness_pct: "{{ target_brightness }}"
                rgb_color:
                  - "{{ target_r }}"
                  - "{{ target_g }}"
                  - "{{ target_b }}"
                transition: 25

            # Update additional lights with color temp
            - if:
                - condition: template
                  value_template: "{{ has_extras }}"
              then:
                - service: light.turn_on
                  target:
                    entity_id: "{{ extras }}"
                  data:
                    brightness_pct: "{{ target_brightness }}"
                    color_temp_kelvin: "{{ target_temp }}"
                    transition: 25

            # Wait before next step (30 seconds)
            - delay:
                seconds: 30

  # =========================================================================
  # PHASE 2: TRANSITION TO THERAPY MODE
  # =========================================================================
  # Only continue if lamp is still on (or temporarily unavailable)
  - condition: template
    value_template: >
      {{ states(beurer) in ['on', 'unavailable'] }}

  # Smooth transition: First go to near-white RGB at high brightness
  - service: light.turn_on
    target:
      entity_id: "{{ beurer }}"
    data:
      brightness_pct: 100
      rgb_color: [255, 255, 250]
      transition: 10

  - if:
      - condition: template
        value_template: "{{ has_extras }}"
    then:
      - service: light.turn_on
        target:
          entity_id: "{{ extras }}"
        data:
          brightness_pct: 100
          color_temp_kelvin: 5000
          transition: 10

  # Wait for transition
  - delay:
      seconds: 12

  # =========================================================================
  # PHASE 3: FULL THERAPY BRIGHTNESS (Native White Mode)
  # =========================================================================
  - condition: template
    value_template: >
      {{ states(beurer) in ['on', 'unavailable'] }}

  # Switch Beurer to native white mode - start at 80% to avoid harsh jump
  # (WHITE mode is more intense than RGB mode at same %)
  - service: light.turn_on
    target:
      entity_id: "{{ beurer }}"
    data:
      brightness_pct: 80
      color_temp_kelvin: 5300
      transition: 5

  - if:
      - condition: template
        value_template: "{{ has_extras }}"
    then:
      - service: light.turn_on
        target:
          entity_id: "{{ extras }}"
        data:
          brightness_pct: 100
          color_temp_kelvin: 5300
          transition: 5

  # Wait a moment, then gradually increase to full therapy brightness
  - delay:
      seconds: 10

  - service: light.turn_on
    target:
      entity_id: "{{ beurer }}"
    data:
      brightness_pct: 100
      color_temp_kelvin: 5300
      transition: 30

  # Wait for therapy duration
  - delay:
      minutes: "{{ therapy_mins }}"

  # =========================================================================
  # PHASE 4: END ACTION
  # =========================================================================
  # Only execute end action if lamp is still on (or temporarily unavailable)
  - condition: template
    value_template: >
      {{ states(beurer) in ['on', 'unavailable'] }}

  - choose:
      # Turn off all lights
      - conditions: "{{ end_behavior == 'off' }}"
        sequence:
          - service: light.turn_off
            target:
              entity_id: "{{ all_lights }}"
            data:
              transition: 5

      # Switch to reading light
      - conditions: "{{ end_behavior == 'reading' }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ all_lights }}"
            data:
              brightness_pct: 80
              color_temp_kelvin: 4000
              transition: 10

      # Stay on: do nothing (lights remain at therapy brightness)

mode: single
max_exceeded: silent
