blueprint:
  name: "Beurer: Evening Wind Down"
  description: |
    Automatically dim your Beurer lamp in the evening to prepare for sleep.

    **How it works:**
    1. Lamp switches to warm, relaxing light at sunset or your chosen time
    2. Gradually dims over the configured period
    3. Turns off at bedtime

    **Why warm light?** Blue light suppresses melatonin production.
    Warm light (2700K) helps your body prepare for sleep.
  domain: automation
  author: Beurer Daylight Lamps Integration
  source_url: https://github.com/moag1000/beurer_daylight_lamps

  input:
    # === REQUIRED ===
    beurer_light:
      name: "Lamp"
      description: "Your Beurer daylight therapy lamp"
      selector:
        entity:
          filter:
            - domain: light
              integration: beurer_daylight_lamps

    # === TRIGGER ===
    trigger_type:
      name: "Start trigger"
      description: "When should the wind-down begin?"
      default: "sunset"
      selector:
        select:
          options:
            - label: "At sunset"
              value: "sunset"
            - label: "30 min after sunset"
              value: "sunset_30"
            - label: "1 hour after sunset"
              value: "sunset_60"
            - label: "Fixed time"
              value: "fixed"
          mode: dropdown

    fixed_time:
      name: "Fixed start time"
      description: "Only used if 'Fixed time' is selected above"
      default: "20:00:00"
      selector:
        time:

    # === WIND-DOWN SETTINGS ===
    wind_down_duration:
      name: "Wind-down duration"
      description: "How long should the gradual dimming take?"
      default: 60
      selector:
        number:
          min: 15
          max: 120
          step: 15
          unit_of_measurement: "min"
          mode: slider

    start_brightness:
      name: "Starting brightness"
      description: "Initial brightness when wind-down begins"
      default: 70
      selector:
        number:
          min: 30
          max: 100
          step: 10
          unit_of_measurement: "%"
          mode: slider

    end_brightness:
      name: "Ending brightness"
      description: "Final brightness before turning off (use 0 to skip and turn off directly)"
      default: 10
      selector:
        number:
          min: 0
          max: 30
          step: 5
          unit_of_measurement: "%"
          mode: slider

    # === SCHEDULE ===
    active_days:
      name: "Active days"
      description: "Which days should this run?"
      default: "daily"
      selector:
        select:
          options:
            - label: "Every day"
              value: "daily"
            - label: "Workdays only (Mon-Fri)"
              value: "workdays"
            - label: "Weekends only (Sat-Sun)"
              value: "weekends"
          mode: dropdown

trigger:
  - platform: sun
    event: sunset
    offset: "00:00:00"
    id: "sunset"
  - platform: sun
    event: sunset
    offset: "00:30:00"
    id: "sunset_30"
  - platform: sun
    event: sunset
    offset: "01:00:00"
    id: "sunset_60"
  - platform: time
    at: !input fixed_time
    id: "fixed"

variables:
  trigger_setting: !input trigger_type
  wind_down_mins: !input wind_down_duration
  brightness_start: !input start_brightness
  brightness_end: !input end_brightness
  light_entity: !input beurer_light
  schedule: !input active_days

condition:
  # Check if correct trigger fired
  - condition: template
    value_template: >
      {{ trigger.id == trigger_setting }}
  # Check day schedule
  - condition: template
    value_template: >
      {% set day = now().weekday() %}
      {% if schedule == 'daily' %}
        true
      {% elif schedule == 'workdays' %}
        {{ day < 5 }}
      {% elif schedule == 'weekends' %}
        {{ day >= 5 }}
      {% else %}
        true
      {% endif %}

action:
  # === Start with warm light ===
  - service: light.turn_on
    target:
      entity_id: "{{ light_entity }}"
    data:
      color_temp_kelvin: 2700
      brightness_pct: "{{ brightness_start }}"

  # === Gradually dim ===
  - variables:
      steps: "{{ (wind_down_mins / 5) | int }}"
      brightness_step: "{{ ((brightness_start - brightness_end) / steps) | round(1) }}"

  - repeat:
      count: "{{ steps }}"
      sequence:
        - delay:
            minutes: 5
        - service: light.turn_on
          target:
            entity_id: "{{ light_entity }}"
          data:
            color_temp_kelvin: 2700
            brightness_pct: >
              {{ [brightness_start - (repeat.index * brightness_step), brightness_end] | max | int }}

  # === Final state ===
  - if:
      - condition: template
        value_template: "{{ brightness_end == 0 }}"
    then:
      - service: light.turn_off
        target:
          entity_id: "{{ light_entity }}"
    else:
      # Stay at end brightness - user will turn off manually or use another automation
      - service: light.turn_on
        target:
          entity_id: "{{ light_entity }}"
        data:
          color_temp_kelvin: 2700
          brightness_pct: "{{ brightness_end }}"

mode: single
max_exceeded: silent
