blueprint:
  name: "Beurer: Focus Work Session"
  description: |
    Optimize your work environment with the right light for focus and productivity.

    **How it works:**
    1. Starts with energizing cool light (5000K) for alertness
    2. Optionally takes regular breaks with warmer light
    3. Ends session after your configured work time

    **Tip:** Cool, bright light (5000K+) promotes alertness and concentration.
    Use this for focused work, studying, or when you need to stay alert.
  domain: automation
  author: Beurer Daylight Lamps Integration
  source_url: https://github.com/moag1000/beurer_daylight_lamps

  input:
    # === REQUIRED ===
    beurer_light:
      name: "Lamp"
      description: "Your Beurer daylight therapy lamp"
      selector:
        entity:
          filter:
            - domain: light
              integration: beurer_daylight_lamps

    # === TRIGGER ===
    trigger_entity:
      name: "Start trigger"
      description: "An entity that triggers the focus session (e.g., input_boolean, button press, or leave empty for manual)"
      default: {}
      selector:
        entity:
          domain:
            - input_boolean
            - binary_sensor
            - switch

    # === WORK SESSION ===
    work_duration:
      name: "Work session length"
      description: "How long is your focused work period?"
      default: 45
      selector:
        number:
          min: 15
          max: 120
          step: 5
          unit_of_measurement: "min"
          mode: slider

    work_brightness:
      name: "Work brightness"
      description: "Brightness during focused work"
      default: 90
      selector:
        number:
          min: 60
          max: 100
          step: 10
          unit_of_measurement: "%"
          mode: slider

    work_color_temp:
      name: "Work color temperature"
      description: "Higher = cooler/more alerting, Lower = warmer/relaxing"
      default: 5000
      selector:
        number:
          min: 4000
          max: 6500
          step: 500
          unit_of_measurement: "K"
          mode: slider

    # === BREAKS ===
    enable_breaks:
      name: "Enable break reminders"
      description: "Briefly change light to remind you to take a break"
      default: false
      selector:
        boolean:

    break_interval:
      name: "Break reminder interval"
      description: "How often should breaks occur? (Pomodoro technique uses 25 min)"
      default: 25
      selector:
        number:
          min: 15
          max: 60
          step: 5
          unit_of_measurement: "min"
          mode: slider

    # === END BEHAVIOR ===
    end_action:
      name: "After work session"
      description: "What should happen when the session ends?"
      default: "relax"
      selector:
        select:
          options:
            - label: "Switch to relaxing light (2700K)"
              value: "relax"
            - label: "Turn off"
              value: "off"
            - label: "Stay on (for multiple sessions)"
              value: "stay_on"
          mode: dropdown

trigger:
  - platform: state
    entity_id: !input trigger_entity
    to: "on"

variables:
  work_mins: !input work_duration
  brightness: !input work_brightness
  color_temp: !input work_color_temp
  breaks_enabled: !input enable_breaks
  break_mins: !input break_interval
  end_behavior: !input end_action
  light_entity: !input beurer_light
  num_breaks: "{{ ((work_mins / break_mins) | int) - 1 }}"

action:
  # === Start Focus Light ===
  - service: light.turn_on
    target:
      entity_id: "{{ light_entity }}"
    data:
      color_temp_kelvin: "{{ color_temp }}"
      brightness_pct: "{{ brightness }}"

  # === Work Session with Optional Breaks ===
  - if:
      - condition: template
        value_template: "{{ breaks_enabled and num_breaks > 0 }}"
    then:
      # Work with break reminders
      - repeat:
          count: "{{ num_breaks }}"
          sequence:
            # Work period
            - delay:
                minutes: "{{ break_mins }}"

            # Break reminder: quick pulse to warmer light
            - service: light.turn_on
              target:
                entity_id: "{{ light_entity }}"
              data:
                color_temp_kelvin: 3000
                brightness_pct: 50

            - delay:
                seconds: 10

            # Back to work light
            - service: light.turn_on
              target:
                entity_id: "{{ light_entity }}"
              data:
                color_temp_kelvin: "{{ color_temp }}"
                brightness_pct: "{{ brightness }}"

      # Final work segment
      - delay:
          minutes: "{{ work_mins - (num_breaks * break_mins) }}"

    else:
      # Simple work session without breaks
      - delay:
          minutes: "{{ work_mins }}"

  # === End Session ===
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ end_behavior == 'off' }}"
        sequence:
          - service: light.turn_off
            target:
              entity_id: "{{ light_entity }}"

      - conditions:
          - condition: template
            value_template: "{{ end_behavior == 'relax' }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ light_entity }}"
            data:
              color_temp_kelvin: 2700
              brightness_pct: 40

    # stay_on: Do nothing

  # Turn off trigger entity if it's an input_boolean
  - service: input_boolean.turn_off
    target:
      entity_id: !input trigger_entity
    continue_on_error: true

mode: restart
max_exceeded: silent
