blueprint:
  name: "Beurer: Morning Light Therapy"
  description: |
    Start your day with a gentle sunrise simulation followed by full light therapy.

    **How it works:**
    1. Lamp starts dim & warm (2700K) at your chosen time
    2. Gradually brightens to full therapy light (5300K)
    3. Stays on for your therapy session
    4. Automatically turns off when done

    **Recommended:** 20-30 min at full brightness for effective light therapy.
  domain: automation
  author: Beurer Daylight Lamps Integration
  source_url: https://github.com/moag1000/beurer_daylight_lamps

  input:
    # === REQUIRED ===
    beurer_light:
      name: "Lamp"
      description: "Your Beurer daylight therapy lamp"
      selector:
        entity:
          filter:
            - domain: light
              integration: beurer_daylight_lamps

    # === SCHEDULE ===
    start_time:
      name: "Wake-up time"
      description: "When should the light therapy start?"
      default: "06:30:00"
      selector:
        time:

    schedule_days:
      name: "Active days"
      description: "Which days should this run?"
      default: "workdays"
      selector:
        select:
          options:
            - label: "Workdays only (Mon-Fri)"
              value: "workdays"
            - label: "Every day"
              value: "daily"
            - label: "Weekends only (Sat-Sun)"
              value: "weekends"
          mode: dropdown

    # === SUNRISE SIMULATION ===
    gradual_start:
      name: "Sunrise duration"
      description: "How long should the gradual wake-up take? Set to 0 for instant full brightness."
      default: 10
      selector:
        number:
          min: 0
          max: 30
          step: 5
          unit_of_measurement: "min"
          mode: slider

    # === THERAPY SESSION ===
    session_duration:
      name: "Therapy duration"
      description: "How long at full brightness (5300K)? Studies recommend 20-30 minutes."
      default: 30
      selector:
        number:
          min: 10
          max: 60
          step: 5
          unit_of_measurement: "min"
          mode: slider

    # === OPTIONAL: END BEHAVIOR ===
    end_behavior:
      name: "After therapy"
      description: "What should happen when the session ends?"
      default: "off"
      selector:
        select:
          options:
            - label: "Turn off"
              value: "off"
            - label: "Stay on (I'll turn it off)"
              value: "stay_on"
            - label: "Dim to reading light (4000K, 50%)"
              value: "reading"
          mode: dropdown

trigger:
  - platform: time
    at: !input start_time

condition:
  - condition: template
    value_template: >
      {% set schedule = schedule_days | default('workdays') %}
      {% set day = now().weekday() %}
      {% if schedule == 'daily' %}
        true
      {% elif schedule == 'workdays' %}
        {{ day < 5 }}
      {% elif schedule == 'weekends' %}
        {{ day >= 5 }}
      {% else %}
        true
      {% endif %}

variables:
  gradual_minutes: !input gradual_start
  session_minutes: !input session_duration
  light_entity: !input beurer_light
  end_action: !input end_behavior
  schedule_days: !input schedule_days

action:
  # === PHASE 1: Sunrise Simulation ===
  - if:
      - condition: template
        value_template: "{{ gradual_minutes > 0 }}"
    then:
      # Start dim and warm
      - service: light.turn_on
        target:
          entity_id: "{{ light_entity }}"
        data:
          color_temp_kelvin: 2700
          brightness_pct: 10

      # Gradually increase brightness and color temperature
      - repeat:
          count: "{{ gradual_minutes }}"
          sequence:
            - delay:
                minutes: 1
            - service: light.turn_on
              target:
                entity_id: "{{ light_entity }}"
              data:
                color_temp_kelvin: >
                  {{ (2700 + (repeat.index * (2600 / gradual_minutes))) | int }}
                brightness_pct: >
                  {{ (10 + (repeat.index * (90 / gradual_minutes))) | int }}

  # === PHASE 2: Full Therapy Brightness ===
  - service: light.turn_on
    target:
      entity_id: "{{ light_entity }}"
    data:
      color_temp_kelvin: 5300
      brightness_pct: 100

  # === PHASE 3: Wait for Session ===
  - delay:
      minutes: "{{ session_minutes }}"

  # === PHASE 4: End Behavior ===
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ end_action == 'off' }}"
        sequence:
          - service: light.turn_off
            target:
              entity_id: "{{ light_entity }}"

      - conditions:
          - condition: template
            value_template: "{{ end_action == 'reading' }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ light_entity }}"
            data:
              color_temp_kelvin: 4000
              brightness_pct: 50

    # stay_on: Do nothing, lamp stays at therapy brightness

mode: single
max_exceeded: silent
